# Generated by Django 5.2.17 on 2026-08-17 13:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('asal_cerita', models.CharField(blank=True, max_length=100)),
                ('kategori_usia', models.CharField(blank=True, max_length=50)),
                ('deskripsi', models.TextField()),
                ('harga', models.PositiveIntegerField(default=0)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('preview', models.FileField(blank=True, null=True, upload_to='previews/')),
                ('file_buku', models.FileField(blank=True, null=True, upload_to='books/')),
                ('berbayar', models.BooleanField(default=True)),
                ('aktif', models.BooleanField(default=True)),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-tanggal_dibuat'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pembeli', models.CharField(max_length=100)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('jumlah', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Menunggu Pembayaran'), ('paid', 'Sudah Dibayar'), ('failed', 'Gagal')], default='pending', max_length=20)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.book')),
            ],
            options={
                'ordering': ['-tanggal'],
            },
        ),
    ]
